# Version of the Icarus theme that is currently used
version: 2.8.1
# Path or URL to the website's icon
favicon: https://oss.kherrisan.cn/logo.jpg
# Additional HTML meta tags in an array.
meta: 
# Path or URL to RSS atom.xml
rss: atom.xml
# Path or URL to the website's logo to be shown on the left of the navigation bar or footer
logo: https://oss.kherrisan.cn/logo.jpg
# Open Graph metadata
# https://hexo.io/docs/helpers.html#open-graph
open_graph:
    # Facebook App ID
    fb_app_id: 
    # Facebook Admin ID
    fb_admins: 
    # Twitter ID
    twitter_id: 
    # Twitter site
    twitter_site: 
    # Google+ profile link
    google_plus: 
# Navigation bar link settings
navbar:
    # Navigation bar menu links
    menu:
        首页: /
        归档: /archives
        分类: /categories
        标签: /tags
        关于: /about
    # Navigation bar links to be shown on the right
    links:
        Download on GitHub:
            icon: fab fa-github
            url: 'https://github.com/ppoffice/hexo-theme-icarus'
# Footer section link settings
footer:
    # Links to be shown on the right of the footer section
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: 'https://creativecommons.org/'
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: 'https://creativecommons.org/licenses/by/4.0/'
        Download on GitHub:
            icon: fab fa-github
            url: 'https://github.com/ppoffice/hexo-theme-icarus'
# Article display settings
article:
    # Code highlight settings
    highlight:
        # Code highlight themes
        # https://github.com/highlightjs/highlight.js/tree/master/src/styles
        theme: solarized-light
        # Show code copying button
        clipboard: true
        # Default folding status of the code blocks. Can be "", "folded", "unfolded"
        fold: unfolded
    # Whether to show article thumbnail images
    thumbnail: true
    # Whether to show estimate article reading time
    readtime: true
# Search plugin settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Search
search:
    # Name of the search plugin
    type: insight
# Comment plugin settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Comment
comment:
    # Name of the comment plugin
    type: valine
    app_id: 1AGA0PAY5WWIJSD1Pwy5SKf4-9Nh9j0Va
    app_key: yMd3tsz0IrFw5tuKWGhQiehm
    placeholder: "找个位子随便坐"                 # 可选填
    notify: false                   # 可选填
    verify: false                   # 可选填
    avatar:                         # 可选填
    avatar_force: false             # 可选填
    meta: ["nick", "mail"]  # 可选填
    page_size: 10                   # 可选填
    visitor: false                  # 可选填
    highlight: true                 # 可选填
    record_ip: false                # 可选填
# Donation entries
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Donation
donate:
    -
        # Donation entry name
        type: alipay
        # Qrcode image URL
        qrcode: 'https://oss.kherrisan.cn/alipay.JPG'
    -
        # Donation entry name
        type: wechat
        # Qrcode image URL
        qrcode: 'https://oss.kherrisan.cn/wechatpay.JPG'
# Share plugin settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Share
share:
    # Share plugin name
    type: sharethis
    # URL to the ShareThis share plugin script
    install_url: 'https://platform-api.sharethis.com/js/sharethis.js#property=5e91d6779dee0c0012ab3bc6&product=inline-share-buttons&cms=website'

# Sidebar settings.
# Please be noted that a sidebar is only visible when it has at least one widget
sidebar:
    # left sidebar settings
    left:
        # Whether the left sidebar is sticky when page scrolls
        # https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/make-a-sidebar-sticky-when-page-scrolls/
        sticky: false
    # right sidebar settings
    right:
        # Whether the right sidebar is sticky when page scrolls
        # https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/make-a-sidebar-sticky-when-page-scrolls/
        sticky: false
# Sidebar widget settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: profile
        hitokoto: true
        # Author name
        author: Kherrisan
        # Author title
        author_title:  科瑞杉
        # Author's current location
        location: 中国-江苏-常州
        # Path or URL to the avatar to be shown in the profile widget
        avatar: https://oss.kherrisan.cn/logo.jpg
        # Email address for the Gravatar to be shown in the profile widget
        gravatar: 
        # Whether to show avatar image rounded or square
        avatar_rounded: false
        # Path or URL for the follow button
        follow_link: 'https://github.com/ppoffice'
        # Links to be shown on the bottom of the profile widget
        social_links:
            Github:
                icon: fab fa-github
                url: 'https://github.com/Kherrisan'
            Wechat:
                icon: fab fa-weixin
                url: ''
            Telegram:
                icon: fab fa-telegram
                url: ''
            Twitter:
                icon: fab fa-twitter
                url: 'https://twitter.com'
            RSS:
                icon: far fa-twitter
                url: 'atom.xml'
    -
        # Widget name
        type: toc
        # Where should the widget be placed, left or right
        position: left
    -
        # Widget name
        type: recent_posts
        # Where should the widget be placed, left or right
        position: right
    -
        # Widget name
        type: tagcloud
        # Where should the widget be placed, left or right
        position: right
    -
        # Widget name
        type: links
        # Where should the widget be placed, left or right
        position: right
        # Links to be shown in the links widget
        links:
            Leetcode: 'https://leetcode.kherrisan.cn'
            ASL: 'https://asl.kherrisan.cn'
            Hexo: 'https://hexo.io'
            PPOffice: 'https://github.com/ppoffice'
# Other plugin settings
plugins:
    # Enable page animations
    animejs: true
    # Enable the lightGallery and Justified Gallery plugins
    # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/gallery-plugin/
    gallery: true
    # Enable the Outdated Browser plugin
    # http://outdatedbrowser.com/
    outdated-browser: true
    # Enable the MathJax plugin
    # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/mathjax-plugin/
    mathjax: true
    # Show the back to top button on mobile devices
    back-to-top: true
    # Google Analytics plugin settings
    # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Google-Analytics
    google-analytics:
        # Google Analytics tracking id
        tracking_id: 
    # Baidu Analytics plugin settings
    # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Baidu-Analytics
    baidu-analytics:
        # Baidu Analytics tracking id
        tracking_id: 
    # Hotjar user feedback plugin
    # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Hotjar
    hotjar:
        # Hotjar site id
        site_id: 
    # Show a loading progress bar at top of the page
    progressbar: true
    # BuSuanZi site/page view counter
    # https://busuanzi.ibruce.info
    busuanzi: true
# CDN provider settings
# https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/
providers:
    # Name or URL of the JavaScript and/or stylesheet CDN provider
    cdn: jsdelivr
    # Name or URL of the webfont CDN provider
    fontcdn: google
    # Name or URL of the webfont Icon CDN provider
    iconcdn: fontawesome
